# Generated by Django 3.2.6 on 2023-01-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
